<a href="https://colab.research.google.com/github/gyeongdong13/Project/blob/main/DEA_%EB%B3%80%EC%88%98%EC%84%A0%ED%83%9D(%EB%8C%80%EC%B6%9C).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

Mounted at /content/drive
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  fonts-nanum
0 upgraded, 1 newly installed, 0 to remove and 16 not upgraded.
Need to get 10.3 MB of archives.
After this operation, 34.1 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 fonts-nanum all 20200506-1 [10.3 MB]
Fetched 10.3 MB in 1s (9,621 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package fonts-nanum.
(Reading database ... 120831 files and directories currently installed.)
Preparing to unpack .../fonts-nanum_20200506-1_all.deb ...
Unpacking fonts-nanum (20200506-1) ...
Setting up fonts-nanum (20200506-1) ...
Processing triggers for fontconfig (2.13.1-4.2ubuntu5) ...
/usr/share/fonts: caching, new cache contents: 0 fonts, 1 dirs
/usr/share/fonts/truetype: caching, new cache contents: 0 fonts, 3 dirs
/usr/share/fonts/truetype/humor-sans: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/liberation: caching, new cache contents: 16 fonts, 0 dirs
/usr/share/fonts/truetype/nanum: caching, new cache contents: 12 fonts, 0 dirs
/usr/local/share/fonts: caching, new cache contents: 0 fonts, 0 dirs
/root/.local/share/fonts: skipping, no such directory
/root/.fonts: skipping, no such directory
/usr/share/fonts/truetype: skipping, looped directory detected
/usr/share/fonts/truetype/humor-sans: skipping, looped directory detected
/usr/share/fonts/truetype/liberation: skipping, looped directory detected
/usr/share/fonts/truetype/nanum: skipping, looped directory detected
/var/cache/fontconfig: cleaning cache directory
/root/.cache/fontconfig: not cleaning non-existent cache directory
/root/.fontconfig: not cleaning non-existent cache directory
fc-cache: succeeded

In [ ]:
loan = pd.read_csv('/content/drive/MyDrive/데이터 청년 캠퍼스/농협 프로젝트/데이터 모음/변수선택(대출).csv', encoding='utf-8')

loan.head()

,사무소명,22년 대출 평잔내역,21년 대출 평잔내역,20년 대출 평잔내역,22년 영업이익,21년 영업이익,20년 영업이익,2022 목표,2022 실적,2022 달성률,...,2020 직원,22년 영업이익(수정),21년 영업이익(수정),20년 영업이익(수정),20년 생명보험 계약건수,20년 생명보험 수수료,21년 생명보험 계약건수,21년 생명보험 수수료,22년 생명보험 계약건수,22년 생명보험 수수료
0,수원축산농협 고등동지점,96447,85121,73231,812,605,414,1303776,2122810,1.628201,...,2,970,901,958,405,27160580,359,20995897,334,18092070
1,수원축산농협 곡반정지점,141679,101423,85298,2575,1327,1128,1851672,2432491,1.313673,...,2,2733,1623,1672,354,29138435,335,20169748,1390,29113539
2,수원축산농협 궐동지점,92599,89463,81933,2637,1642,1245,1007295,1454936,1.444399,...,3,2795,1938,1789,391,24501830,360,18522629,316,16896770
3,수원축산농협 기안지점,80500,76805,69074,1919,1121,817,687047,922337,1.342466,...,3,2077,1417,1361,541,28719628,441,21513970,381,16779843
4,수원축산농협 남수원지점,84319,79034,71568,2444,1487,1058,1024475,1375094,1.342243,...,2,2602,1783,1602,768,51270957,679,35765554,589,27945195

In [ ]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
df = sc.fit_transform(loan.drop(columns=["사무소명", "22년 영업이익", "21년 영업이익", "20년 영업이익", "2022 목표", "2022 실적", "2021 목표", "2021 실적", "2020 목표", "2020 실적"]))
columns=["22년 평잔내역", "21년 평잔내역","20년 평잔내역", "2022 달성률", "2021 달성률", "2020 달성률", "2022 직원", "2021 직원", "2020 직원", "22년 영업이익(수정)", "21년 영업이익(수정)", "20년 영업이익(수정)", "20년 생명보험 계약건수", "20년 생명보험 수수료", "21년 생명보험 계약건수", "21년 생명보험 수수료", "22년 생명보험 계약건수", "22년 생명보험 수수료"]
df = pd.DataFrame(df, columns=columns)
df.head(5)

,22년 평잔내역,21년 평잔내역,20년 평잔내역,2022 달성률,2021 달성률,2020 달성률,2022 직원,2021 직원,2020 직원,22년 영업이익(수정),21년 영업이익(수정),20년 영업이익(수정),20년 생명보험 계약건수,20년 생명보험 수수료,21년 생명보험 계약건수,21년 생명보험 수수료,22년 생명보험 계약건수,22년 생명보험 수수료
0,-0.012146,-0.133792,-0.124316,0.031586,-0.267122,-0.154861,-0.542326,-0.507093,-0.565685,-1.138048,-0.768199,-0.712750,-0.226680,-0.144134,-0.238603,-0.049941,-0.272475,0.123152
1,1.166295,0.245934,0.176570,-0.411226,-0.659633,0.483618,1.843909,-0.507093,-0.565685,1.139692,0.179977,0.517161,-0.349785,-0.038763,-0.300389,-0.107434,3.369723,1.309944
2,-0.112398,-0.032653,0.092665,-0.227181,-0.633736,0.001907,1.843909,1.352247,0.989949,1.219794,0.593654,0.718701,-0.260474,-0.285779,-0.236029,-0.222060,-0.334558,-0.005558
3,-0.427617,-0.327498,-0.227969,-0.370689,-0.351864,0.657095,-0.542326,-0.507093,0.989949,0.292161,-0.090555,-0.018557,0.101600,-0.061075,-0.027500,-0.013887,-0.110370,-0.018149
4,-0.328119,-0.275578,-0.165782,-0.371003,-0.660292,-0.021860,-0.542326,-0.507093,-0.565685,0.970445,0.390099,0.396581,0.649538,1.140349,0.585215,0.977908,0.607033,1.184136

# 20년 직원 추출현황

In [ ]:
# 종속변수 지정(2020년)
y = loan["2020 직원"]
y.head(5)

0    2
1    2
2    3
3    3
4    2
Name: 2020 직원, dtype: int64

In [ ]:
# 독립변수 지정
X = df[['20년 평잔내역', '20년 영업이익(수정)', '20년 생명보험 계약건수', '20년 생명보험 수수료']]
X.head(5)

   20년 평잔내역  20년 영업이익(수정)  20년 생명보험 계약건수  20년 생명보험 수수료
0 -0.124316     -0.712750      -0.226680     -0.144134
1  0.176570      0.517161      -0.349785     -0.038763
2  0.092665      0.718701      -0.260474     -0.285779
3 -0.227969     -0.018557       0.101600     -0.061075
4 -0.165782      0.396581       0.649538      1.140349

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((19, 4), (3, 4), (19,), (3,))

In [ ]:
from sklearn.linear_model import Lasso
X_train_lasso, X_val_lasso, y_train_lasso, y_val_lasso = train_test_split(X, y, test_size=0.2, random_state=0)

max_score = 0
max_alpha = 0
alphas = [10 ** i for i in range(-1, 6)]
for alpha in alphas: # alpha를 0.1부터 10000까지 10배씩 증가
    lasso_clf = Lasso(alpha=alpha) #라쏘 분류기 선언
    lasso_clf.fit(X_train_lasso, y_train_lasso) #학습
    score = lasso_clf.score(X_val_lasso, y_val_lasso) #검정 데이터셋에 대해 정확도를 측정
    if score > max_score: #정확도가 이전의 정확도 최대값보다 크면 최대값을 변경
        max_score = score
        max_alpha = alpha
print('Max alpha {:.3f} at max validation score {:.3f}'.format(max_alpha, max_score))

Max alpha 0.100 at max validation score 0.385

In [ ]:
from sklearn.linear_model import Lasso
import numpy as np

lasso_clf = Lasso(alpha=0.1)
lasso_clf.fit(X_train, y_train)

print('#Used features count: {}'.format(np.sum(lasso_clf.coef_ != 0)), 'out of', X.shape[1])

#Used features count: 1 out of 4

In [ ]:
# 회귀계수가 0이 아닌 변수들의 컬럼 이름 확인
selected_feature_names = X.columns[lasso_clf.coef_ != 0]
print("Selected feature names:", selected_feature_names.tolist())

Selected feature names: ['20년 평잔내역']

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

X = df[['20년 평잔내역']]
y = loan["2020 직원"]

# 선형 회귀 모델 생성
model = LinearRegression()

# 모델 학습
model.fit(X, y)

# 예측 값 계산
predicted_y = model.predict(X)

# 결정 계수 계산
r2 = r2_score(y, predicted_y)
print("R-squared:", r2)

R-squared: 0.6594695243730331

In [ ]:
X = df[['20년 평잔내역']]
y = loan["2020 직원"]

import statsmodels.api as sm
# 상수항 추가
X = sm.add_constant(X)

# 선형 회귀 모델 적합
linear_model = sm.OLS(y, X)
linear_results = linear_model.fit()

# 결과 출력
print(linear_results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                2020 직원   R-squared:                       0.659
Model:                            OLS   Adj. R-squared:                  0.642
Method:                 Least Squares   F-statistic:                     38.73
Date:                Tue, 22 Aug 2023   Prob (F-statistic):           4.45e-06
Time:                        07:50:06   Log-Likelihood:                -9.6454
No. Observations:                  22   AIC:                             23.29
Df Residuals:                      20   BIC:                             25.47
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.3636      0.084     28.179      0.000       2.189       2.539
20년 평잔내역       0.5220      0.084      6.223      0.000       0.347       0.697
==============================================================================
Omnibus:                        4.075   Durbin-Watson:                   1.535
Prob(Omnibus):                  0.130   Jarque-Bera (JB):                2.729
Skew:                           0.690   Prob(JB):                        0.255
Kurtosis:                       1.964   Cond. No.                         1.00
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [ ]:
import statsmodels.api as sm

# 독립 변수
X = df[['20년 평잔내역']]
# 종속 변수 (빈도 데이터)
y = loan["2020 직원"]

# 상수항 추가
X = sm.add_constant(X)

# 포아송 회귀 모델 적합
poisson_model = sm.GLM(y, X, family=sm.families.Poisson())
poisson_results = poisson_model.fit()

# 결과 출력
print(poisson_results.summary())

                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:                2020 직원   No. Observations:                   22
Model:                            GLM   Df Residuals:                       20
Model Family:                 Poisson   Df Model:                            1
Link Function:                    Log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -30.713
Date:                Sun, 13 Aug 2023   Deviance:                       1.1074
Time:                        14:39:42   Pearson chi2:                     1.16
No. Iterations:                     4   Pseudo R-squ. (CS):             0.1009
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.8393      0.141      5.938      0.000       0.562       1.116
20년 평잔내역       0.1964      0.124      1.586      0.113      -0.046       0.439
==============================================================================

# 21년 직원 추출현황

In [ ]:
# 종속변수 지정(2021년)
y = loan["2021 직원"]
y.head(5)

0    2
1    2
2    3
3    2
4    2
Name: 2021 직원, dtype: int64

In [ ]:
# 독립변수 지정
X = df[['21년 평잔내역', '21년 영업이익(수정)', '21년 생명보험 계약건수', '21년 생명보험 수수료']]
X.head(5)

   21년 평잔내역  21년 영업이익(수정)  21년 생명보험 계약건수  21년 생명보험 수수료
0 -0.133792     -0.768199      -0.238603     -0.049941
1  0.245934      0.179977      -0.300389     -0.107434
2 -0.032653      0.593654      -0.236029     -0.222060
3 -0.327498     -0.090555      -0.027500     -0.013887
4 -0.275578      0.390099       0.585215      0.977908

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((19, 4), (3, 4), (19,), (3,))

In [ ]:
X_train_lasso, X_val_lasso, y_train_lasso, y_val_lasso = train_test_split(X, y, test_size=0.2, random_state=0)

max_score = 0
max_alpha = 0
alphas = [10 ** i for i in range(-1, 6)]
for alpha in alphas: # alpha를 0.1부터 10000까지 10배씩 증가
    lasso_clf = Lasso(alpha=alpha) #라쏘 분류기 선언
    lasso_clf.fit(X_train_lasso, y_train_lasso) #학습
    score = lasso_clf.score(X_val_lasso, y_val_lasso) #검정 데이터셋에 대해 정확도를 측정
    if score > max_score: #정확도가 이전의 정확도 최대값보다 크면 최대값을 변경
        max_score = score
        max_alpha = alpha
print('Max alpha {:.3f} at max validation score {:.3f}'.format(max_alpha, max_score))

Max alpha 0.100 at max validation score 0.552

In [ ]:
from sklearn.linear_model import Lasso
import numpy as np

lasso_clf = Lasso(alpha=0.1)
lasso_clf.fit(X_train, y_train)

print('#Used features count: {}'.format(np.sum(lasso_clf.coef_ != 0)), 'out of', X.shape[1])

#Used features count: 2 out of 4

In [ ]:
# 회귀계수가 0이 아닌 변수들의 컬럼 이름 확인
selected_feature_names = X.columns[lasso_clf.coef_ != 0]
print("Selected feature names:", selected_feature_names.tolist())

Selected feature names: ['21년 평잔내역', '21년 영업이익(수정)']

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

X = df[['21년 평잔내역', '21년 영업이익(수정)']]
y = loan["2021 직원"]

# 선형 회귀 모델 생성
model = LinearRegression()

# 모델 학습
model.fit(X, y)

# 예측 값 계산
predicted_y = model.predict(X)

# 결정 계수 계산
r2 = r2_score(y, predicted_y)
print("R-squared:", r2)

R-squared: 0.6919792510528338

In [ ]:
# 상수항 추가
X = sm.add_constant(X)

# 선형 회귀 모델 적합
linear_model = sm.OLS(y, X)
linear_results = linear_model.fit()

# 결과 출력
print(linear_results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                2021 직원   R-squared:                       0.692
Model:                            OLS   Adj. R-squared:                  0.660
Method:                 Least Squares   F-statistic:                     21.34
Date:                Sun, 13 Aug 2023   Prob (F-statistic):           1.39e-05
Time:                        14:42:43   Log-Likelihood:                -4.6183
No. Observations:                  22   AIC:                             15.24
Df Residuals:                      19   BIC:                             18.51
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.2727      0.068     33.189      0.000       2.129       2.416
21년 평잔내역       0.2845      0.152      1.870      0.077      -0.034       0.603
21년 영업이익       0.1746      0.152      1.148      0.265      -0.144       0.493
==============================================================================
Omnibus:                        4.589   Durbin-Watson:                   2.138
Prob(Omnibus):                  0.101   Jarque-Bera (JB):                3.667
Skew:                           0.995   Prob(JB):                        0.160
Kurtosis:                       2.795   Cond. No.                         4.21
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [ ]:
# 상수항 추가
X = sm.add_constant(X)

# 포아송 회귀 모델 적합
poisson_model = sm.GLM(y, X, family=sm.families.Poisson())
poisson_results = poisson_model.fit()

# 결과 출력
print(poisson_results.summary())

                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:                2021 직원   No. Observations:                   22
Model:                            GLM   Df Residuals:                       19
Model Family:                 Poisson   Df Model:                            2
Link Function:                    Log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -30.183
Date:                Sun, 13 Aug 2023   Deviance:                      0.70011
Time:                        14:43:13   Pearson chi2:                    0.732
No. Iterations:                     4   Pseudo R-squ. (CS):            0.07826
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.8043      0.144      5.601      0.000       0.523       1.086
21년 평잔내역       0.0996      0.304      0.327      0.743      -0.496       0.696
21년 영업이익       0.0810      0.313      0.259      0.796      -0.532       0.694
==============================================================================

# 22년 직원 추출현황

In [ ]:
# 종속변수 지정(2022년)
y = loan["2022 직원"]
y.head(5)

0    2
1    3
2    3
3    2
4    2
Name: 2022 직원, dtype: int64

In [ ]:
# 독립변수 지정
X = df[['22년 평잔내역', '22년 영업이익(수정)', '22년 생명보험 계약건수', '22년 생명보험 수수료']]
X.head(5)

   22년 평잔내역  22년 영업이익(수정)  22년 생명보험 계약건수  22년 생명보험 수수료
0 -0.012146     -1.138048      -0.272475      0.123152
1  1.166295      1.139692       3.369723      1.309944
2 -0.112398      1.219794      -0.334558     -0.005558
3 -0.427617      0.292161      -0.110370     -0.018149
4 -0.328119      0.970445       0.607033      1.184136

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((19, 4), (3, 4), (19,), (3,))

In [ ]:
X_train_lasso, X_val_lasso, y_train_lasso, y_val_lasso = train_test_split(X, y, test_size=0.2, random_state=0)

max_score = 0
max_alpha = 0
alphas = [10 ** i for i in range(-1, 6)]
for alpha in alphas: # alpha를 0.1부터 10000까지 10배씩 증가
    lasso_clf = Lasso(alpha=alpha) #라쏘 분류기 선언
    lasso_clf.fit(X_train_lasso, y_train_lasso) #학습
    score = lasso_clf.score(X_val_lasso, y_val_lasso) #검정 데이터셋에 대해 정확도를 측정
    if score > max_score: #정확도가 이전의 정확도 최대값보다 크면 최대값을 변경
        max_score = score
        max_alpha = alpha
print('Max alpha {:.3f} at max validation score {:.3f}'.format(max_alpha, max_score))

Max alpha 0.100 at max validation score 0.453

In [ ]:
from sklearn.linear_model import Lasso
import numpy as np

lasso_clf = Lasso(alpha=0.1)
lasso_clf.fit(X_train, y_train)

print('#Used features count: {}'.format(np.sum(lasso_clf.coef_ != 0)), 'out of', X.shape[1])

#Used features count: 2 out of 4

In [ ]:
# 회귀계수가 0이 아닌 변수들의 컬럼 이름 확인
selected_feature_names = X.columns[lasso_clf.coef_ != 0]
print("Selected feature names:", selected_feature_names.tolist())

Selected feature names: ['22년 평잔내역', '22년 생명보험 계약건수']

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

X = df[['22년 평잔내역', '22년 생명보험 계약건수']]
y = df["2022 직원"]

# 선형 회귀 모델 생성
model = LinearRegression()

# 모델 학습
linear_results = model.fit(X, y)

# 예측 값 계산
predicted_y = model.predict(X)

# 결정 계수 계산
r2 = r2_score(y, predicted_y)
print("R-squared:", r2)

R-squared: 0.6438519611163926

In [ ]:
X = df[['22년 평잔내역', '22년 생명보험 계약건수']]
y = loan["2022 직원"]

import statsmodels.api as sm
# 상수항 추가
X = sm.add_constant(X)

# 선형 회귀 모델 적합
linear_model = sm.OLS(y, X)
linear_results = linear_model.fit()

# 결과 출력
print(linear_results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                2022 직원   R-squared:                       0.644
Model:                            OLS   Adj. R-squared:                  0.606
Method:                 Least Squares   F-statistic:                     17.17
Date:                Tue, 22 Aug 2023   Prob (F-statistic):           5.50e-05
Time:                        07:39:54   Log-Likelihood:               -0.72638
No. Observations:                  22   AIC:                             7.453
Df Residuals:                      19   BIC:                             10.73
Df Model:                           2
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const             2.2273      0.057     38.819      0.000       2.107       2.347
22년 평잔내역          0.2958      0.067      4.395      0.000       0.155       0.437
22년 생명보험 계약건수     0.0678      0.067      1.007      0.326      -0.073       0.209
==============================================================================
Omnibus:                       17.185   Durbin-Watson:                   1.637
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               18.625
Skew:                           1.668   Prob(JB):                     9.03e-05
Kurtosis:                       6.031   Cond. No.                         1.79
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [ ]:
import statsmodels.api as sm

# 독립 변수
X = df[['22년 평잔내역', '22년 생명보험 계약건수']]
# 종속 변수 (빈도 데이터)
y = loan["2022 직원"]

# 상수항 추가
X = sm.add_constant(X)

# 포아송 회귀 모델 적합
poisson_model = sm.GLM(y, X, family=sm.families.Poisson())
poisson_results = poisson_model.fit()

# 결과 출력
print(poisson_results.summary())

                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:                2022 직원   No. Observations:                   22
Model:                            GLM   Df Residuals:                       19
Model Family:                 Poisson   Df Model:                            2
Link Function:                    Log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -29.966
Date:                Tue, 22 Aug 2023   Deviance:                      0.54018
Time:                        07:40:24   Pearson chi2:                    0.577
No. Iterations:                     3   Pseudo R-squ. (CS):            0.04773
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
const             0.7902      0.144      5.475      0.000       0.507       1.073
22년 평잔내역          0.1244      0.156      0.799      0.424      -0.181       0.429
22년 생명보험 계약건수     0.0308      0.156      0.197      0.843      -0.275       0.337
=================================================================================