<a href="https://colab.research.google.com/github/gyeongdong13/Project/blob/main/%EB%8D%B0%EC%9D%B4%ED%84%B0_%EC%A0%84%EC%B2%98%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
bus_station = pd.read_csv('/content/drive/MyDrive/데이터 청년 캠퍼스/농협 프로젝트/데이터 모음/버스정류장.csv', encoding='utf-8')

bus_station.head()

,정류장번호,정류장명,위도,경도,정보수집일시,모바일단축번호,도시코드,도시명,관리도시명
0,GGB200000001,하광교느티나무,37.317600,127.016900,2.020000e+13,1165,31010,수원시,경기도
1,GGB200000002,하광교,37.315933,127.019167,2.020000e+13,1173,31010,수원시,경기도
2,GGB200000003,비석거리입구,37.313233,127.021017,2.020000e+13,1180,31010,수원시,경기도
3,GGB200000004,문암골,37.309083,127.027717,2.020000e+13,1196,31010,수원시,경기도
4,GGB200000005,광교산입구.경기대수원캠퍼스,37.301433,127.031517,2.020000e+13,1205,31010,수원시,경기도

In [ ]:
bank_location = pd.read_csv('/content/drive/MyDrive/데이터 청년 캠퍼스/농협 프로젝트/데이터 모음/축협 지점 별 좌표.csv', encoding='utf-8')

bank_location.head()

,코드,사무소명,장소,위도,경도
0,179614,수원축산농협 고등동지점,경기도 수원시 팔달구 팔달로 53 2층,37.274305,127.003074
1,179740,수원축산농협 곡반정지점,경기도 수원시 권선구 곡반정동 555 2층,37.238963,127.030718
2,170354,수원축산농협 궐동지점,경기도 오산시 궐동 615-5 농협,37.160438,127.053935
3,170370,수원축산농협 기안지점,경기도 화성시 기안동 371-2 보보스프라자 2층 206호,37.222727,126.974341
4,170794,수원축산농협 남수원지점,경기도 수원시 권선구 세류동 1147 미영아파트,37.247453,127.014513

In [ ]:
import math
from math import sin, cos, sqrt, atan2

def haversine_distance(lat1, lon1, lat2, lon2):
    R = 6371  # 지구의 반지름 (단위: km)
    dlat = math.radians(lat2 - lat1)
    dlon = math.radians(lon2 - lon1)
    a = math.sin(dlat/2) * math.sin(dlat/2) + math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) * math.sin(dlon/2) * math.sin(dlon/2)
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1-a))
    distance = R * c
    return distance


# 300m 내 정류장 개수
def count_nearby_bus_stops_300(bus, bank) :
  nearby_bus_stops = 0
  for _, bus_stop in bank.iterrows() :
    distance = haversine_distance(
        bus["위도"], bus['경도'],
        bus_stop["위도"], bus_stop["경도"]
    )
    if distance <= 0.3 :
      nearby_bus_stops += 1
  return nearby_bus_stops

In [ ]:
bank_location["반경 0.3km 내 버스정류장 개수"] = bank_location.apply(lambda x : count_nearby_bus_stops_300(x, bus_station),axis=1)

print(bank_location)

        코드              사무소명                                   장소         위도  \
0   179614      수원축산농협 고등동지점                경기도 수원시 팔달구 팔달로 53 2층  37.274305
1   179740      수원축산농협 곡반정지점              경기도 수원시 권선구 곡반정동 555 2층  37.238963
2   170354       수원축산농협 궐동지점                  경기도 오산시 궐동 615-5 농협  37.160438
3   170370       수원축산농협 기안지점     경기도 화성시 기안동 371-2 보보스프라자 2층 206호  37.222727
4   170794      수원축산농협 남수원지점           경기도 수원시 권선구 세류동 1147 미영아파트  37.247453
5   170846       수원축산농협 남양지점                 경기도 화성시 남양읍 남양리 1365  37.212343
6   170772     수원축산농협 동탄목동지점        경기 화성시 동탄순환대로20길 124 A동 2층 농협  37.182641
7   170770  수원축산농협 동탄테크노밸리지점         경기도 화성시 영천동 산24-1 센테라아이티타워2차  37.210588
8   170817       수원축산농협 발안지점               경기도 화성시 향남읍 장짐리 273-21  37.135510
9   170859       수원축산농협 병점지점                    경기도 화성시 병점동 317-3  37.206072
10  170820       수원축산농협 삼환지점  경기도 수원시 권선구 구운동 462 삼환아파트 상가 2층, 5호  37.283313
11  172394       수원축산농협 세교지점         경기도 오산시 금암동 516-1 센타프라자 201호  37.176381
12  170773   수원축산농협 송산그린시티지점             경기도 화성시 새솔동 76-3 2층 201호  37.285677
13  170765    수원축산농협 수원시청역지점            경기도 수원시 팔달구 인계동 1124-5 1층  37.261623
14  179627      수원축산농협 오목천지점               경기도 수원시 권선구 오목천동 551-1  37.240386
15  170833       수원축산농협 오산지점                   경기도 오산시 오산동 919-17  37.156361
16  170777      수원축산농협 율전동지점               경기도 수원시 장안구 율전동 553 1층  37.305450
17  170778      수원축산농협 정자동지점                경기도 수원시 장안구 정자동 80-21  37.292164
18  170367       수원축산농협 진안지점         경기도 화성시 병점동 844-5 리더스프라자201호  37.214703
19  170804       수원축산농협 탑동지점                 경기도 수원시 권선구 탑동 863-1  37.268698
20  170768      수원축산농협 파장동지점             경기도 수원시 장안구 파장동 570-8 2층  37.309264
21  170781      수원축산농협 화서동지점        경기도 수원시 팔달구 화서동 206-8 신우상가아파트  37.281171

            경도  반경 0.3km 내 버스정류장 개수
0   127.003074                   11
1   127.030718                    3
2   127.053935                    5
3   126.974341                    7
4   127.014513                    4
5   126.823946                    4
6   127.124684                    9
7   127.099551                    5
8   126.911201                    9
9   127.040269                    9
10  126.978751                    7
11  127.044510                    6
12  126.816918                    2
13  127.033410                    6
14  126.969624                    8
15  127.077956                    9
16  126.970860                   10
17  127.006999                    4
18  127.043879                   14
19  126.975779                    8
20  126.988783                    8
21  126.997075                    9

In [ ]:
# 500m 내 정류장 개수
def count_nearby_bus_stops_500(bus, bank) :
  nearby_bus_stops = 0
  for _, bus_stop in bank.iterrows() :
    distance = haversine_distance(
        bus["위도"], bus['경도'],
        bus_stop["위도"], bus_stop["경도"]
    )
    if distance <= 0.5 :
      nearby_bus_stops += 1
  return nearby_bus_stops


bank_location["반경 0.5km 내 버스정류장 개수"] = bank_location.apply(lambda x : count_nearby_bus_stops_500(x, bus_station),axis=1)
print(bank_location)

        코드              사무소명                                   장소         위도  \
0   179614      수원축산농협 고등동지점                경기도 수원시 팔달구 팔달로 53 2층  37.274305
1   179740      수원축산농협 곡반정지점              경기도 수원시 권선구 곡반정동 555 2층  37.238963
2   170354       수원축산농협 궐동지점                  경기도 오산시 궐동 615-5 농협  37.160438
3   170370       수원축산농협 기안지점     경기도 화성시 기안동 371-2 보보스프라자 2층 206호  37.222727
4   170794      수원축산농협 남수원지점           경기도 수원시 권선구 세류동 1147 미영아파트  37.247453
5   170846       수원축산농협 남양지점                 경기도 화성시 남양읍 남양리 1365  37.212343
6   170772     수원축산농협 동탄목동지점        경기 화성시 동탄순환대로20길 124 A동 2층 농협  37.182641
7   170770  수원축산농협 동탄테크노밸리지점         경기도 화성시 영천동 산24-1 센테라아이티타워2차  37.210588
8   170817       수원축산농협 발안지점               경기도 화성시 향남읍 장짐리 273-21  37.135510
9   170859       수원축산농협 병점지점                    경기도 화성시 병점동 317-3  37.206072
10  170820       수원축산농협 삼환지점  경기도 수원시 권선구 구운동 462 삼환아파트 상가 2층, 5호  37.283313
11  172394       수원축산농협 세교지점         경기도 오산시 금암동 516-1 센타프라자 201호  37.176381
12  170773   수원축산농협 송산그린시티지점             경기도 화성시 새솔동 76-3 2층 201호  37.285677
13  170765    수원축산농협 수원시청역지점            경기도 수원시 팔달구 인계동 1124-5 1층  37.261623
14  179627      수원축산농협 오목천지점               경기도 수원시 권선구 오목천동 551-1  37.240386
15  170833       수원축산농협 오산지점                   경기도 오산시 오산동 919-17  37.156361
16  170777      수원축산농협 율전동지점               경기도 수원시 장안구 율전동 553 1층  37.305450
17  170778      수원축산농협 정자동지점                경기도 수원시 장안구 정자동 80-21  37.292164
18  170367       수원축산농협 진안지점         경기도 화성시 병점동 844-5 리더스프라자201호  37.214703
19  170804       수원축산농협 탑동지점                 경기도 수원시 권선구 탑동 863-1  37.268698
20  170768      수원축산농협 파장동지점             경기도 수원시 장안구 파장동 570-8 2층  37.309264
21  170781      수원축산농협 화서동지점        경기도 수원시 팔달구 화서동 206-8 신우상가아파트  37.281171

            경도  반경 0.3km 내 버스정류장 개수  반경 0.5km 내 버스정류장 개수
0   127.003074                   11                   22
1   127.030718                    3                    9
2   127.053935                    5                   10
3   126.974341                    7                   20
4   127.014513                    4                   12
5   126.823946                    4                    4
6   127.124684                    9                   14
7   127.099551                    5                   10
8   126.911201                    9                   14
9   127.040269                    9                   26
10  126.978751                    7                   18
11  127.044510                    6                    9
12  126.816918                    2                    9
13  127.033410                    6                    9
14  126.969624                    8                    9
15  127.077956                    9                   14
16  126.970860                   10                   31
17  127.006999                    4                   13
18  127.043879                   14                   23
19  126.975779                    8                   14
20  126.988783                    8                   15
21  126.997075                    9                   23